#!/usr/bin/env python3
"""
sap_ordinals_to_def.py — produce an OpenADS .def file whose
ordinals match an existing ace64.dll / ace32.dll the user
already legally possesses.

Background
----------
Some applications were linked against an `ace32.lib` / `ace64.lib`
import library that records `Ads*` imports BY ORDINAL rather than
by name. When the application is later loaded against OpenADS'
drop-in DLL, the Windows loader looks up each ordinal in the new
DLL — and OpenADS exports by name only, so the ordinals don't
match. Symptom: "the ordinal NNN could not be located in the
dynamic link library ace64.dll".

Fix
---
1. On the same machine that ships the original SAP DLL, run:

       dumpbin /exports ace64.dll > ace64-exports.txt

   (Available with any Visual Studio install; ships in the
   "Developer Command Prompt".)

2. Run this script on the produced text:

       python tools/scripts/sap_ordinals_to_def.py \\
              ace64-exports.txt > openads_ace_ordinals.def

3. Rebuild OpenADS pointing the DLL target at the new .def:

       cmake -DOPENADS_ACE_DEF=openads_ace_ordinals.def -B build/ord
       cmake --build build/ord --target openads_ace --config Release

The resulting `ace64.dll` keeps the same export NAMES as our
upstream `src/openads_ace.def` AND the same ORDINAL numbers the
user's binary expects — drop-in works without recompiling the
calling application.

Legal note
----------
The script consumes `dumpbin` output (a plain text listing of an
exported-symbols table from a DLL the user legally possesses). It
does **not** read or copy any SAP-owned binary code. The function
NAMES it round-trips are public — they are the same symbols
Harbour's `contrib/rddads` calls by name. The ORDINAL numbers are
metadata, not protected expression. The OpenADS source contains
zero SAP-derived code; only this user-supplied number table.
"""

import sys, re, os

if len(sys.argv) != 2:
    print(__doc__)
    sys.exit(2)

src = sys.argv[1]
if not os.path.exists(src):
    print(f"file not found: {src}", file=sys.stderr)
    sys.exit(1)

# dumpbin /exports output looks like:
#         ordinal hint RVA      name
#               1    0 00001234 AdsConnect60 = AdsConnect60
#               2    1 0000125A AdsDisconnect = AdsDisconnect
# We only care about lines with both an ordinal and a name.
pat = re.compile(r"^\s*(\d+)\s+\w+\s+\w+\s+(\w+)")

print("; OpenADS ACE-compatible DLL exports — ordinals matching the")
print("; user-supplied SAP ace32.dll / ace64.dll dumpbin output.")
print("; Generated by tools/scripts/sap_ordinals_to_def.py.")
print(";")
print("; Symbol names are the same publicly-callable Ads* names that")
print("; Harbour's contrib/rddads sources reference by name. The")
print("; @N annotations are user-supplied numeric metadata.")
print("LIBRARY")
print("EXPORTS")

with open(src, "r", encoding="latin-1") as f:
    for line in f:
        m = pat.match(line)
        if not m: continue
        ordinal = int(m.group(1))
        name    = m.group(2)
        # Skip header / footer noise.
        if not name.startswith("Ads") and not name.startswith("_Ads"):
            continue
        print(f"    {name}    @{ordinal}")
