#define _TEST_ADS_
REQUEST ADS
#define _TESTRDD "ADS"
#include "rddtst.prg"

FUNCTION test_main()

RDDTESTC {0,.T.,.T.,.F.}, LOCAL n
RDDTESTF "ADS", {0,.T.,.T.,.F.}, RDDSETDEFAULT()
RDDTESTC {1,.T.,.T.,.F.}, USE "_tst" SHARED
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {1,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTC {1,.T.,.F.,.F.}, SET DELETE ON
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {1,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTC {1,.T.,.F.,.F.}, SET DELETE OFF
RDDTESTC {1,.T.,.T.,.F.}, INDEX on FNUM tag TG_N to "_tst"
RDDTESTC {1,.T.,.T.,.F.}, INDEX on FSTR tag TG_C to "_tst"
RDDTESTF "TG_C", {1,.T.,.T.,.F.}, ORDSETFOCUS()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {1,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTC {1,.T.,.F.,.F.}, SET DELETE ON
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {1,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF .F., {1,.T.,.T.,.F.}, DBSEEK("", .T.,.F.)
RDDTESTF .F., {1,.T.,.T.,.F.}, DBSEEK("", .T.,.T.)
RDDTESTF .F., {1,.T.,.T.,.F.}, DBSEEK("", .F.,.F.)
RDDTESTF .F., {1,.T.,.T.,.F.}, DBSEEK("", .F.,.T.)
RDDTESTC {1,.T.,.T.,.F.}, SET DELETE OFF
RDDTESTC {15,.F.,.F.,.F.}, for n := 1 to 15                     ; dbappend()                             ; replace FNUM with int( ( n + 2 ) / 3 ) ; replace FSTR with chr( FNUM +48 )      ; next
RDDTESTF NIL, {15,.F.,.F.,.F.}, dbcommit()
RDDTESTF NIL, {15,.F.,.F.,.F.}, dbunlock()
RDDTESTF "TG_C", {15,.F.,.F.,.F.}, ORDSETFOCUS(1)
RDDTESTF "TG_N", {15,.F.,.F.,.F.}, ORDSETFOCUS()
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(0,.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(0,.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(0.5,.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(0.5,.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(1.0,.T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(1.0,.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(2.0,.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(2.0,.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(2.5,.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(2.5,.T.,.T.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(5.0,.T.,.F.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(5.0,.T.,.T.)
RDDTESTF "TG_N", {13,.F.,.F.,.T.}, ORDSETFOCUS(2)
RDDTESTF "TG_C", {13,.F.,.F.,.T.}, ORDSETFOCUS()
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("", .T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("", .T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("1",.T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("1",.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK("2",.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK("2",.T.,.T.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK("3",.T.,.F.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK("3",.T.,.T.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK("4",.T.,.F.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK("4",.T.,.T.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK("5",.T.,.F.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK("5",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("", .T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("", .T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("1",.T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK("1",.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK("2",.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK("2",.T.,.T.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK("3",.T.,.F.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK("3",.T.,.T.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK("4",.T.,.F.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK("4",.T.,.T.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK("5",.T.,.F.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK("5",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.T.)
RDDTESTC {15,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst" DESCEND
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("0",.T.,.T.)
RDDTESTF .T., {3,.F.,.F.,.T.}, DBSEEK("1",.T.,.F.)
RDDTESTF .T., {3,.F.,.F.,.T.}, DBSEEK("1",.T.,.T.)
RDDTESTF .T., {6,.F.,.F.,.T.}, DBSEEK("2",.T.,.F.)
RDDTESTF .T., {6,.F.,.F.,.T.}, DBSEEK("2",.T.,.T.)
RDDTESTF .T., {9,.F.,.F.,.T.}, DBSEEK("3",.T.,.F.)
RDDTESTF .T., {9,.F.,.F.,.T.}, DBSEEK("3",.T.,.T.)
RDDTESTF .T., {12,.F.,.F.,.T.}, DBSEEK("4",.T.,.F.)
RDDTESTF .T., {12,.F.,.F.,.T.}, DBSEEK("4",.T.,.T.)
RDDTESTF .T., {15,.F.,.F.,.T.}, DBSEEK("5",.T.,.F.)
RDDTESTF .T., {15,.F.,.F.,.T.}, DBSEEK("5",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK("6",.T.,.T.)
RDDTESTC {1,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst"
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(0)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(5)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(5)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(5)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {10,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(10)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOTO(12)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOTO(12)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBGOTO(14)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF "TG_C", {15,.F.,.F.,.F.}, ORDSETFOCUS(0)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-10)
RDDTESTC {7,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst" FOR FNUM>2 .AND. FNUM<=4
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOTO(12)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOTO(12)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBGOTO(14)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTC {1,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst" FOR FNUM<>2 .AND. FNUM<4
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {10,.F.,.F.,.F.}, DBGOTO(10)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {10,.F.,.F.,.F.}, DBGOTO(10)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBGOTO(14)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {1,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {9,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTC {16,.T.,.T.,.F.}, INDEX on FSTR tag TG_C to "_tst" FOR FNUM==6
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTC {15,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst" FOR RECNO()<>5 DESCEND
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBGOTO(5)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBGOTO(5)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTC {1,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst" FOR RECNO()<>5
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBGOTO(5)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBGOTO(5)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF "TG_C", {8,.F.,.F.,.F.}, ORDSETFOCUS(0)
RDDTESTC {8,.F.,.F.,.F.}, SET DELETE ON
RDDTESTF .T., {8,.F.,.F.,.F.}, FLOCK()
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBGOTO(3)
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBGOTO(14)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBGOTO(15)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBDELETE()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBCOMMIT()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBUNLOCK()
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-10)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBSKIP(5)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBSKIP(6)
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-7)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(8)
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-20)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(10)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(5)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBSKIP(-6)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(7)
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-8)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(20)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-20)
RDDTESTF .T., {2,.T.,.F.,.F.}, FLOCK()
RDDTESTC {16,.F.,.T.,.F.}, DELETE ALL
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBUNLOCK()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF .T., {7,.F.,.F.,.F.}, DBRLOCK()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBRECALL()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBUNLOCK()
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBGOTO(11)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBGOTO(11)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTC {16,.F.,.T.,.F.}, SET DELETE OFF
RDDTESTF .T., {16,.T.,.T.,.F.}, FLOCK()
RDDTESTC {16,.F.,.T.,.F.}, RECALL ALL
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBUNLOCK()
RDDTESTC {16,.F.,.T.,.F.}, SET DELETE ON
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBCOMMIT()
RDDTESTF "", {15,.F.,.F.,.F.}, ORDSETFOCUS(1)
RDDTESTC {15,.F.,.F.,.F.}, SET DELETE ON
RDDTESTF .T., {15,.F.,.F.,.F.}, FLOCK()
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTO(1)
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBGOTO(3)
RDDTESTF NIL, {3,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBGOTO(6)
RDDTESTF NIL, {6,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBGOTO(13)
RDDTESTF NIL, {13,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBGOTO(14)
RDDTESTF NIL, {14,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBGOTO(15)
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBDELETE()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(16)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBDELETE()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBCOMMIT()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBUNLOCK()
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-10)
RDDTESTF NIL, {10,.F.,.F.,.F.}, DBSKIP(5)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBSKIP(6)
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-7)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(8)
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-20)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(10)
RDDTESTF NIL, {8,.F.,.F.,.F.}, DBSKIP(-5)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(5)
RDDTESTF NIL, {5,.F.,.F.,.F.}, DBSKIP(-6)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(7)
RDDTESTF NIL, {2,.F.,.F.,.F.}, DBSKIP(-8)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(20)
RDDTESTF NIL, {12,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {2,.T.,.F.,.F.}, DBSKIP(-20)
RDDTESTF .T., {2,.T.,.F.,.F.}, FLOCK()
RDDTESTC {16,.F.,.T.,.F.}, DELETE ALL
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBCOMMIT()
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBUNLOCK()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTOP()
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(0)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {16,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {16,.T.,.T.,.F.}, DBGOTO(0)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBGOTO(7)
RDDTESTF .T., {7,.F.,.F.,.F.}, DBRLOCK()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBRECALL()
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBUNLOCK()
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.T.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {4,.F.,.F.,.F.}, DBGOTO(4)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(1)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBGOTO(11)
RDDTESTF NIL, {7,.F.,.F.,.F.}, DBSKIP(-1)
RDDTESTF NIL, {11,.F.,.F.,.F.}, DBGOTO(11)
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBSKIP(1)
RDDTESTC {16,.F.,.T.,.F.}, SET DELETE OFF
RDDTESTF .T., {16,.T.,.T.,.F.}, FLOCK()
RDDTESTC {16,.F.,.T.,.F.}, RECALL ALL
RDDTESTF NIL, {16,.F.,.T.,.F.}, DBUNLOCK()
RDDTESTC {16,.F.,.T.,.F.}, SET DELETE ON
RDDTESTF NIL, {1,.F.,.F.,.F.}, DBGOTOP()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBGOBOTTOM()
RDDTESTF NIL, {15,.F.,.F.,.F.}, DBCOMMIT()
RDDTESTC {1,.F.,.F.,.F.}, INDEX on FSTR tag TG_C to "_tst"
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr(" ",10)+" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr(" ",10)+" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("0",10)+" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("0",10)+" ",.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(padr("1",10)+" ",.T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(padr("1",10)+" ",.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(padr("2",10)+" ",.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(padr("2",10)+" ",.T.,.T.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK(padr("3",10)+" ",.T.,.F.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK(padr("3",10)+" ",.T.,.T.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK(padr("4",10)+" ",.T.,.F.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK(padr("4",10)+" ",.T.,.T.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(padr("5",10)+" ",.T.,.F.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(padr("5",10)+" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("6",10)+" ",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("6",10)+" ",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr(" ",10)+"*",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr(" ",10)+"*",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("0",10)+"*",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("0",10)+"*",.T.,.T.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(padr("1",10)+"*",.T.,.F.)
RDDTESTF .T., {1,.F.,.F.,.T.}, DBSEEK(padr("1",10)+"*",.T.,.T.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(padr("2",10)+"*",.T.,.F.)
RDDTESTF .T., {4,.F.,.F.,.T.}, DBSEEK(padr("2",10)+"*",.T.,.T.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK(padr("3",10)+"*",.T.,.F.)
RDDTESTF .T., {7,.F.,.F.,.T.}, DBSEEK(padr("3",10)+"*",.T.,.T.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK(padr("4",10)+"*",.T.,.F.)
RDDTESTF .T., {10,.F.,.F.,.T.}, DBSEEK(padr("4",10)+"*",.T.,.T.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(padr("5",10)+"*",.T.,.F.)
RDDTESTF .T., {13,.F.,.F.,.T.}, DBSEEK(padr("5",10)+"*",.T.,.T.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("6",10)+"*",.T.,.F.)
RDDTESTF .F., {16,.F.,.T.,.F.}, DBSEEK(padr("6",10)+"*",.T.,.T.)

RETURN NIL
