// openads_serverd — interactive first-run setup wizard (see setup_wizard.h).

#include "tools/serverd/setup_wizard.h"

#include <cctype>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <string>

namespace openads::serverd {

namespace {

std::string trim(const std::string& s) {
    std::size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) --e;
    return s.substr(b, e - b);
}

// Ask `question`, showing `def` as the default. Returns the trimmed answer,
// or `def` if the user just hit Enter. Returns false if stdin hit EOF (e.g.
// the wizard was run non-interactively with no input) so the caller can
// abort instead of looping forever.
bool ask(const std::string& question, const std::string& def,
         std::string& out) {
    if (def.empty())
        std::printf("%s: ", question.c_str());
    else
        std::printf("%s [%s]: ", question.c_str(), def.c_str());
    std::fflush(stdout);
    std::string line;
    if (!std::getline(std::cin, line)) return false;
    std::string t = trim(line);
    out = t.empty() ? def : t;
    return true;
}

bool ask_yesno(const std::string& question, bool def, bool& out) {
    std::string ans;
    if (!ask(question + (def ? " (Y/n)" : " (y/N)"), def ? "y" : "n", ans))
        return false;
    char c = ans.empty() ? (def ? 'y' : 'n')
                         : static_cast<char>(std::tolower(
                               static_cast<unsigned char>(ans[0])));
    out = (c == 'y');
    return true;
}

bool is_digits(const std::string& s) {
    if (s.empty()) return false;
    for (char c : s)
        if (c < '0' || c > '9') return false;
    return true;
}

// Quote a value for an INI line only if needed. INI values here are literal
// (no escape processing), so a Windows path with backslashes is fine as-is.
void write_ini(std::ostream& os, const std::string& host,
               const std::string& port, const std::string& backlog,
               const std::string& data, bool studio,
               const std::string& http_port, const std::string& http_user) {
    os << "# openads.ini — generated by `openads_serverd --setup`.\n"
       << "# Point the daemon here with:  openads_serverd --config "
          "openads.ini\n"
       << "# Command-line flags given as well override these keys.\n\n"
       << "[server]\n"
       << "host = " << host << "\n"
       << "port = " << port << "\n"
       << "backlog = " << backlog << "\n"
       << "data = " << data << "\n";
    if (studio) {
        os << "http_port = " << http_port << "\n";
        if (!http_user.empty())
            os << "http_user = " << http_user << "\n";
        else
            os << "# http_user = admin:change-me   # console is open\n";
    } else {
        os << "# http_port = 6263   # uncomment to enable the Studio "
              "web console\n";
    }
}

#if !defined(_WIN32)
// Write a service unit (systemd on Linux, launchd on macOS) that launches
// the daemon with `--config <ini>`, and print the commands to enable it.
void write_posix_service(const std::string& exe_path,
                         const std::string& ini_path,
                         const std::string& data_dir) {
#if defined(__APPLE__)
    const std::string unit = "com.openads.serverd.plist";
    std::ofstream f(unit, std::ios::binary);
    if (!f) {
        std::printf("  (could not write %s — skipping)\n", unit.c_str());
        return;
    }
    f << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
      << "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"\n"
      << "  \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
      << "<plist version=\"1.0\">\n<dict>\n"
      << "    <key>Label</key><string>com.openads.serverd</string>\n"
      << "    <key>ProgramArguments</key>\n    <array>\n"
      << "        <string>" << exe_path << "</string>\n"
      << "        <string>--config</string><string>" << ini_path
      << "</string>\n    </array>\n"
      << "    <key>WorkingDirectory</key><string>" << data_dir
      << "</string>\n"
      << "    <key>RunAtLoad</key><true/>\n"
      << "    <key>KeepAlive</key><dict><key>Crashed</key><true/></dict>\n"
      << "    <key>StandardOutPath</key>"
         "<string>/var/log/openads-serverd.out.log</string>\n"
      << "    <key>StandardErrorPath</key>"
         "<string>/var/log/openads-serverd.err.log</string>\n"
      << "</dict>\n</plist>\n";
    f.close();
    std::printf(
        "\nWrote %s. To start at boot (needs sudo):\n"
        "  sudo cp %s /Library/LaunchDaemons/\n"
        "  sudo launchctl bootstrap system "
        "/Library/LaunchDaemons/%s\n"
        "  sudo launchctl kickstart -kp system/com.openads.serverd\n",
        unit.c_str(), unit.c_str(), unit.c_str());
#else
    const std::string unit = "openads-serverd.service";
    std::ofstream f(unit, std::ios::binary);
    if (!f) {
        std::printf("  (could not write %s — skipping)\n", unit.c_str());
        return;
    }
    f << "[Unit]\n"
      << "Description=OpenADS Database Server\n"
      << "Documentation=https://github.com/FiveTechSoft/OpenADS\n"
      << "After=network-online.target\n"
      << "Wants=network-online.target\n\n"
      << "[Service]\n"
      << "Type=simple\n"
      << "ExecStart=" << exe_path << " --config " << ini_path << "\n"
      << "WorkingDirectory=" << data_dir << "\n"
      << "Restart=on-failure\n"
      << "RestartSec=5s\n"
      << "NoNewPrivileges=true\n"
      << "ProtectSystem=strict\n"
      << "ProtectHome=true\n"
      << "PrivateTmp=true\n"
      << "ReadWritePaths=" << data_dir << "\n"
      << "RestrictAddressFamilies=AF_INET AF_INET6\n"
      << "LimitNOFILE=65535\n\n"
      << "[Install]\n"
      << "WantedBy=multi-user.target\n";
    f.close();
    std::printf(
        "\nWrote %s. To start at boot (needs sudo):\n"
        "  sudo cp %s /etc/systemd/system/\n"
        "  sudo systemctl daemon-reload\n"
        "  sudo systemctl enable --now openads-serverd\n",
        unit.c_str(), unit.c_str());
#endif
}
#endif  // !_WIN32

}  // namespace

bool run_setup_wizard(const std::string& exe_path, SetupResult& out) {
    std::printf(
        "\nOpenADS server setup\n"
        "====================\n"
        "Answer a few questions; a config file is written that the server\n"
        "(or a service) reads with --config. Press Enter to accept the\n"
        "[default] shown.\n\n");

    std::string host, port, data, ini_path;
    if (!ask("Bind address (0.0.0.0 = all interfaces)", "0.0.0.0", host))
        return false;

    for (;;) {
        if (!ask("Wire (TCP) port clients connect to", "6262", port))
            return false;
        if (!is_digits(port) || std::stol(port) > 65535) {
            std::printf("  ! port must be a number 0..65535\n");
            continue;
        }
        if (port == "6262")
            std::printf(
                "  note: 6262 is the historical ADS port. If an "
                "Advantage service still\n        runs on this host, pick "
                "another (e.g. 6263) to avoid a bind clash.\n");
        break;
    }

    if (!ask("Data directory (where tables live)", ".", data)) return false;

    bool studio = false;
    std::string http_port, http_user;
    if (!ask_yesno("Enable the Studio web console (the ARC replacement)?",
                   false, studio))
        return false;
    if (studio) {
        for (;;) {
            if (!ask("  Studio HTTP port", "6263", http_port)) return false;
            if (is_digits(http_port) && std::stol(http_port) <= 65535) break;
            std::printf("  ! port must be a number 0..65535\n");
        }
        std::string user;
        if (!ask("  Studio admin user (blank = open console)", "", user))
            return false;
        if (!user.empty()) {
            std::string pass;
            if (!ask("  Studio admin password", "", pass)) return false;
            http_user = user + ":" + pass;
        }
    }

    if (!ask("Write the config to", "openads.ini", ini_path)) return false;

    {
        std::ifstream exists(ini_path);
        if (exists.good()) {
            bool ow = false;
            if (!ask_yesno("  " + ini_path + " exists — overwrite?", false,
                           ow))
                return false;
            if (!ow) {
                std::printf("Aborted; nothing written.\n");
                return false;
            }
        }
    }

    bool autostart = false;
    if (!ask_yesno("Start OpenADS automatically at boot (install a service)?",
                   false, autostart))
        return false;

    std::ofstream f(ini_path, std::ios::binary);
    if (!f) {
        std::printf("error: cannot write %s\n", ini_path.c_str());
        return false;
    }
    write_ini(f, host, port, "16", data, studio, http_port, http_user);
    f.close();
    out.ini_path = ini_path;

    std::printf("\nWrote %s:\n", ini_path.c_str());
    std::printf("  bind        %s:%s\n", host.c_str(), port.c_str());
    std::printf("  data dir    %s\n", data.c_str());
    if (studio)
        std::printf("  Studio      http://%s:%s/%s\n", host.c_str(),
                    http_port.c_str(),
                    http_user.empty() ? " (open)" : " (login required)");
    std::printf("\nRun it now with:\n  openads_serverd --config %s\n",
                ini_path.c_str());

    out.want_service = false;
    if (autostart) {
#if defined(_WIN32)
        out.want_service = true;  // main() registers the Windows Service
#else
        write_posix_service(exe_path, ini_path, data);
#endif
    }
    (void)exe_path;  // unused on Windows
    return true;
}

}  // namespace openads::serverd
