#include "doctest.h"
#include "openads/ace.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

// Stage a DBF with `nfields` numeric columns named C01, C02, ... each `width`
// wide with zero decimals. Mirrors the synthetic-DBF style of the sibling
// abi_sql_insert_test fixture.
fs::path stage_numeric_dbf(const fs::path& dir, int nfields, int width) {
    fs::create_directories(dir);
    auto p = dir / "data.dbf";
    fs::remove(p);
    std::vector<std::uint8_t> file;
    auto push = [&](const void* d, std::size_t n) {
        const auto* b = static_cast<const std::uint8_t*>(d);
        file.insert(file.end(), b, b + n);
    };
    const int hdr_len = 32 + 32 * nfields + 1;
    const int rec_len = 1 + width * nfields;
    std::array<std::uint8_t, 32> hdr{};
    hdr[0]  = 0x03;
    hdr[4]  = 0;
    hdr[8]  = static_cast<std::uint8_t>(hdr_len & 0xFF);
    hdr[9]  = static_cast<std::uint8_t>((hdr_len >> 8) & 0xFF);
    hdr[10] = static_cast<std::uint8_t>(rec_len & 0xFF);
    hdr[11] = static_cast<std::uint8_t>((rec_len >> 8) & 0xFF);
    push(hdr.data(), hdr.size());
    for (int i = 1; i <= nfields; ++i) {
        std::array<std::uint8_t, 32> fd{};
        char nm[12];
        std::snprintf(nm, sizeof(nm), "C%02d", i);
        std::strncpy(reinterpret_cast<char*>(fd.data()), nm, 11);
        fd[11] = 'N';
        fd[16] = static_cast<std::uint8_t>(width);
        fd[17] = 0;
        push(fd.data(), fd.size());
    }
    file.push_back(0x0D);
    std::ofstream(p, std::ios::binary).write(
        reinterpret_cast<const char*>(file.data()),
        static_cast<std::streamsize>(file.size()));
    return p;
}

std::string get_field_trimmed(ADSHANDLE hTable, const char* field) {
    UNSIGNED8 fld[16] = {0};
    std::strncpy(reinterpret_cast<char*>(fld), field, 15);
    UNSIGNED8 buf[64] = {0};
    UNSIGNED32 cap = sizeof(buf);
    if (AdsGetField(hTable, fld, buf, &cap, 0) != 0) return "<err>";
    std::string s(reinterpret_cast<const char*>(buf), cap);
    while (!s.empty() && (s.front() == ' ')) s.erase(s.begin());
    while (!s.empty() && (s.back() == ' ' || s.back() == '\0')) s.pop_back();
    return s;
}

}  // namespace

// REGRESSION — named parameter substitution must not let a short placeholder
// (:p1) match as a prefix of a longer one (:p10, :p11, ...). With >= 10 named
// params the buggy textual substitution corrupted the values of the
// double-digit placeholders. A multi-row prepared INSERT (as generated by an
// ORM) is the real-world trigger.
TEST_CASE("AdsExecuteSQL: named params with prefix overlap (:p1 vs :p10) keep values intact") {
    auto dir = fs::temp_directory_path() / "openads_named_param_prefix";
    std::error_code ec;
    fs::remove_all(dir, ec);
    const int NF = 12;          // C01..C12
    stage_numeric_dbf(dir, NF, 6);

    UNSIGNED8 srv[256];
    std::memcpy(srv, dir.string().c_str(), dir.string().size() + 1);
    ADSHANDLE hConn = 0;
    REQUIRE(AdsConnect60(srv, ADS_LOCAL_SERVER, nullptr, nullptr, 0, &hConn) == 0);

    ADSHANDLE hStmt = 0;
    REQUIRE(AdsCreateSQLStatement(hConn, &hStmt) == 0);

    // INSERT INTO data (C01,...,C12) VALUES (:p1,:p2,...,:p12)
    std::string sql = "INSERT INTO data (";
    for (int i = 1; i <= NF; ++i) { if (i > 1) sql += ","; char c[8]; std::snprintf(c, sizeof(c), "C%02d", i); sql += c; }
    sql += ") VALUES (";
    for (int i = 1; i <= NF; ++i) { if (i > 1) sql += ","; sql += ":p" + std::to_string(i); }
    sql += ")";
    std::vector<UNSIGNED8> sqlbuf(sql.begin(), sql.end());
    sqlbuf.push_back('\0');
    REQUIRE(AdsPrepareSQL(hStmt, sqlbuf.data()) == 0);

    // bind p_i = i * 100  (100, 200, ..., 1200) — distinct, double-digit at i>=10
    for (int i = 1; i <= NF; ++i) {
        std::string pname = "p" + std::to_string(i);
        UNSIGNED8 fld[16] = {0};
        std::strncpy(reinterpret_cast<char*>(fld), pname.c_str(), 15);
        REQUIRE(AdsSetDouble(hStmt, fld, static_cast<double>(i * 100)) == 0);
    }
    ADSHANDLE hCur = 0xDEADBEEF;
    REQUIRE(AdsExecuteSQL(hStmt, &hCur) == 0);

    UNSIGNED8 leaf[16] = "data";
    ADSHANDLE hTable = 0;
    REQUIRE(AdsOpenTable(hConn, leaf, leaf, ADS_CDX, 1, 1, 0, 1, &hTable) == 0);
    UNSIGNED32 cnt = 0;
    REQUIRE(AdsGetRecordCount(hTable, 0, &cnt) == 0);
    CHECK(cnt == 1);
    REQUIRE(AdsGotoTop(hTable) == 0);

    for (int i = 1; i <= NF; ++i) {
        char c[8]; std::snprintf(c, sizeof(c), "C%02d", i);
        CHECK(get_field_trimmed(hTable, c) == std::to_string(i * 100));
    }

    REQUIRE(AdsCloseTable(hTable) == 0);
    REQUIRE(AdsCloseSQLStatement(hStmt) == 0);
    REQUIRE(AdsDisconnect(hConn) == 0);
    fs::remove_all(dir, ec);
}

// RCB 2026-07-03 — AdsSetNull on a statement parameter previously stored
// the quoted literal '' (via AdsSetEmpty -> AdsSetString), which the SQL
// parser accepted as a plain string literal and silently wrote wrong data
// instead of failing or storing NULL. It now substitutes the bare NULL
// keyword, and parse_insert/parse_update recognize it (InsertLiteral::
// is_null) instead of erroring out of read_numeric_literal with a 7200.
// Confirms the row is actually written (not a parse failure) and the NULL
// column comes back blank while the sibling bound param keeps its value.
TEST_CASE("AdsExecuteSQL: AdsSetNull on a statement parameter") {
    auto dir = fs::temp_directory_path() / "openads_named_param_null";
    std::error_code ec;
    fs::remove_all(dir, ec);
    stage_numeric_dbf(dir, 2, 6);

    UNSIGNED8 srv[256];
    std::memcpy(srv, dir.string().c_str(), dir.string().size() + 1);
    ADSHANDLE hConn = 0;
    REQUIRE(AdsConnect60(srv, ADS_LOCAL_SERVER, nullptr, nullptr, 0, &hConn) == 0);

    ADSHANDLE hStmt = 0;
    REQUIRE(AdsCreateSQLStatement(hConn, &hStmt) == 0);

    std::string sql = "INSERT INTO data (C01,C02) VALUES (:p1,:p2)";
    std::vector<UNSIGNED8> sqlbuf(sql.begin(), sql.end());
    sqlbuf.push_back('\0');
    REQUIRE(AdsPrepareSQL(hStmt, sqlbuf.data()) == 0);

    UNSIGNED8 p1[] = "p1";
    UNSIGNED8 p2[] = "p2";
    REQUIRE(AdsSetNull(hStmt, p1) == 0);
    REQUIRE(AdsSetDouble(hStmt, p2, 42.0) == 0);

    ADSHANDLE hCur = 0xDEADBEEF;
    REQUIRE(AdsExecuteSQL(hStmt, &hCur) == 0);

    UNSIGNED8 leaf[16] = "data";
    ADSHANDLE hTable = 0;
    REQUIRE(AdsOpenTable(hConn, leaf, leaf, ADS_CDX, 1, 1, 0, 1, &hTable) == 0);
    UNSIGNED32 cnt = 0;
    REQUIRE(AdsGetRecordCount(hTable, 0, &cnt) == 0);
    CHECK(cnt == 1);
    REQUIRE(AdsGotoTop(hTable) == 0);
    CHECK(get_field_trimmed(hTable, "C01") == "");
    CHECK(get_field_trimmed(hTable, "C02") == "42");

    REQUIRE(AdsCloseTable(hTable) == 0);
    REQUIRE(AdsCloseSQLStatement(hStmt) == 0);
    REQUIRE(AdsDisconnect(hConn) == 0);
    fs::remove_all(dir, ec);
}

// RCB 2026-07-03 — same NULL-literal support for UPDATE ... SET col = :param
// (UpdateAssign::value reuses InsertLiteral, so this exercises the parser
// branch added in parse_update alongside parse_insert's).
TEST_CASE("AdsExecuteSQL: AdsSetNull on an UPDATE statement parameter") {
    auto dir = fs::temp_directory_path() / "openads_named_param_null_update";
    std::error_code ec;
    fs::remove_all(dir, ec);
    stage_numeric_dbf(dir, 2, 6);

    UNSIGNED8 srv[256];
    std::memcpy(srv, dir.string().c_str(), dir.string().size() + 1);
    ADSHANDLE hConn = 0;
    REQUIRE(AdsConnect60(srv, ADS_LOCAL_SERVER, nullptr, nullptr, 0, &hConn) == 0);

    UNSIGNED8 leaf[16] = "data";
    ADSHANDLE hTable = 0;
    REQUIRE(AdsOpenTable(hConn, leaf, leaf, ADS_CDX, 1, 1, 0, 1, &hTable) == 0);
    REQUIRE(AdsAppendRecord(hTable) == 0);
    UNSIGNED8 fC01[] = "C01";
    UNSIGNED8 fC02[] = "C02";
    REQUIRE(AdsSetDouble(hTable, fC01, 7.0) == 0);
    REQUIRE(AdsSetDouble(hTable, fC02, 8.0) == 0);
    REQUIRE(AdsCloseTable(hTable) == 0);

    ADSHANDLE hStmt = 0;
    REQUIRE(AdsCreateSQLStatement(hConn, &hStmt) == 0);
    std::string sql = "UPDATE data SET C01 = :p1";
    std::vector<UNSIGNED8> sqlbuf(sql.begin(), sql.end());
    sqlbuf.push_back('\0');
    REQUIRE(AdsPrepareSQL(hStmt, sqlbuf.data()) == 0);
    UNSIGNED8 p1[] = "p1";
    REQUIRE(AdsSetNull(hStmt, p1) == 0);
    ADSHANDLE hCur = 0xDEADBEEF;
    REQUIRE(AdsExecuteSQL(hStmt, &hCur) == 0);

    REQUIRE(AdsOpenTable(hConn, leaf, leaf, ADS_CDX, 1, 1, 0, 1, &hTable) == 0);
    REQUIRE(AdsGotoTop(hTable) == 0);
    CHECK(get_field_trimmed(hTable, "C01") == "");
    CHECK(get_field_trimmed(hTable, "C02") == "8");

    REQUIRE(AdsCloseTable(hTable) == 0);
    REQUIRE(AdsCloseSQLStatement(hStmt) == 0);
    REQUIRE(AdsDisconnect(hConn) == 0);
    fs::remove_all(dir, ec);
}

// REGRESSION — the substituted SQL must not be clipped to a fixed buffer.
// A prepared INSERT whose final text exceeds 4096 bytes (e.g. a multi-row
// INSERT) was truncated, producing a parse error or lost rows.
TEST_CASE("AdsExecuteSQL: substituted SQL larger than 4096 bytes is not truncated") {
    auto dir = fs::temp_directory_path() / "openads_named_param_bufsize";
    std::error_code ec;
    fs::remove_all(dir, ec);
    const int NF = 6;           // C01..C06
    stage_numeric_dbf(dir, NF, 6);

    UNSIGNED8 srv[256];
    std::memcpy(srv, dir.string().c_str(), dir.string().size() + 1);
    ADSHANDLE hConn = 0;
    REQUIRE(AdsConnect60(srv, ADS_LOCAL_SERVER, nullptr, nullptr, 0, &hConn) == 0);

    ADSHANDLE hStmt = 0;
    REQUIRE(AdsCreateSQLStatement(hConn, &hStmt) == 0);

    // Multi-row INSERT with enough rows that the final text crosses 4096 bytes.
    // Asserting only the row count isolates the buffer-truncation bug from the
    // value-corruption bug: truncation cuts mid-tuple, so AdsExecuteSQL either
    // fails to parse or lands fewer rows; scrambled values would not change cnt.
    const int ROWS = 300;       // final SQL well over 4096 bytes
    std::string sql = "INSERT INTO data (C01,C02,C03,C04,C05,C06) VALUES ";
    int pidx = 1;
    for (int r = 0; r < ROWS; ++r) {
        if (r > 0) sql += ",";
        sql += "(";
        for (int j = 0; j < NF; ++j) { if (j > 0) sql += ","; sql += ":p" + std::to_string(pidx++); }
        sql += ")";
    }
    std::vector<UNSIGNED8> sqlbuf(sql.begin(), sql.end());
    sqlbuf.push_back('\0');
    REQUIRE(AdsPrepareSQL(hStmt, sqlbuf.data()) == 0);

    // bind every param p_k = k (so row r, col j holds r*6 + j + 1)
    for (int k = 1; k < pidx; ++k) {
        std::string pname = "p" + std::to_string(k);
        UNSIGNED8 fld[16] = {0};
        std::strncpy(reinterpret_cast<char*>(fld), pname.c_str(), 15);
        REQUIRE(AdsSetDouble(hStmt, fld, static_cast<double>(k)) == 0);
    }
    ADSHANDLE hCur = 0xDEADBEEF;
    CHECK(AdsExecuteSQL(hStmt, &hCur) == 0);   // truncation -> parse error

    UNSIGNED8 leaf[16] = "data";
    ADSHANDLE hTable = 0;
    REQUIRE(AdsOpenTable(hConn, leaf, leaf, ADS_CDX, 1, 1, 0, 1, &hTable) == 0);
    UNSIGNED32 cnt = 0;
    REQUIRE(AdsGetRecordCount(hTable, 0, &cnt) == 0);
    CHECK(cnt == static_cast<UNSIGNED32>(ROWS));

    REQUIRE(AdsCloseTable(hTable) == 0);
    REQUIRE(AdsCloseSQLStatement(hStmt) == 0);
    REQUIRE(AdsDisconnect(hConn) == 0);
    fs::remove_all(dir, ec);
}
