#include "doctest.h"

#include "sql_backend/sql_acl_store.h"
#include "sql_backend/sql_ddl.h"
#include "sql_backend/sql_system_catalog.h"

using openads::sql_backend::SqlDdlColumn;
using openads::sql_backend::SqlDdlDialect;
using openads::sql_backend::build_create_index_ddl;
using openads::sql_backend::build_create_table_ddl;
using openads::sql_backend::build_system_catalog_sql;
using openads::sql_backend::IndexExprKind;
using openads::sql_backend::rewrite_system_select_sql;

TEST_CASE("sql_ddl: Oracle CREATE TABLE uses VARCHAR2 and IDENTITY") {
    std::vector<SqlDdlColumn> cols{
        {"ID", 'A', 4, 0},
        {"NAME", 'C', 40, 0},
    };
    auto ddl = build_create_table_ddl(SqlDdlDialect::Oracle, "items", cols);
    REQUIRE(ddl.has_value());
    const std::string& sql = ddl.value();
    CHECK(sql.find("VARCHAR2(40)") != std::string::npos);
    CHECK(sql.find("GENERATED BY DEFAULT AS IDENTITY") != std::string::npos);
    CHECK(sql.find("PRIMARY KEY") != std::string::npos);
}

TEST_CASE("sql_ddl: Oracle CREATE INDEX has no IF NOT EXISTS") {
    auto ddl = build_create_index_ddl(
        SqlDdlDialect::Oracle, "items", "TAG1",
        IndexExprKind::Column, "NAME");
    REQUIRE(ddl.has_value());
    const std::string& sql = ddl.value();
    CHECK(sql.find("IF NOT EXISTS") == std::string::npos);
    CHECK(sql.find("CREATE INDEX") != std::string::npos);
}

TEST_CASE("sql_system_catalog: Oracle tables/columns catalog SQL") {
    auto tables = build_system_catalog_sql(SqlDdlDialect::Oracle, "tables");
    auto columns = build_system_catalog_sql(SqlDdlDialect::Oracle, "columns");
    REQUIRE(tables.has_value());
    REQUIRE(columns.has_value());
    CHECK(tables.value().find("user_tables") != std::string::npos);
    CHECK(columns.value().find("user_tab_columns") != std::string::npos);
}

TEST_CASE("sql_system_catalog: rewrite system.tables for Oracle dialect") {
    auto rewritten = rewrite_system_select_sql(
        SqlDdlDialect::Oracle, "SELECT Name FROM system.tables");
    REQUIRE(rewritten.has_value());
    CHECK(rewritten.value().find("user_tables") != std::string::npos);
    CHECK(rewritten.value().find("_openads_sys") != std::string::npos);
}

TEST_CASE("sql_acl_store: Oracle ACL DDL uses user_tables guard") {
    const auto ddl = openads::sql_backend::acl_table_ddl(SqlDdlDialect::Oracle);
    CHECK(ddl.find("user_tables") != std::string::npos);
    CHECK(ddl.find("OPENADS$ACL") != std::string::npos);
}

TEST_CASE("sql_acl_store: Oracle member grant uses MERGE") {
    const auto sql = openads::sql_backend::member_table_ddl(SqlDdlDialect::Oracle);
    CHECK(sql.find("OPENADS$MEMBER") != std::string::npos);
}